
all: snespad-trapthem.prg standard-3buttons.prg

snespad-trapthem.prg: snespad-trapthem.asm
	acme -f cbm -o snespad-trapthem.prg snespad-trapthem.asm

standard-3buttons.prg: standard-3buttons.asm
	acme -f cbm -o standard-3buttons.prg standard-3buttons.asm
