TARGETS = \
noise_writeback_check_8_to_8_old.prg \
noise_writeback_check_8_to_8_new.prg \
noise_writeback_check_8_to_9_old.prg \
noise_writeback_check_8_to_9_new.prg \
noise_writeback_check_8_to_A_old.prg \
noise_writeback_check_8_to_A_new.prg \
noise_writeback_check_8_to_B_old.prg \
noise_writeback_check_8_to_B_new.prg \
noise_writeback_check_8_to_C_old.prg \
noise_writeback_check_8_to_D_old.prg \
noise_writeback_check_8_to_D_new.prg \
noise_writeback_check_8_to_E_old.prg \
noise_writeback_check_8_to_E_new.prg \
noise_writeback_check_8_to_F_old.prg \
noise_writeback_check_8_to_F_new.prg \
noise_writeback_check_9_to_8_old.prg \
noise_writeback_check_9_to_8_new.prg \
noise_writeback_check_9_to_9_old.prg \
noise_writeback_check_9_to_9_new.prg \
noise_writeback_check_9_to_A_old.prg \
noise_writeback_check_9_to_B_old.prg \
noise_writeback_check_9_to_B_new.prg \
noise_writeback_check_9_to_C_old.prg \
noise_writeback_check_9_to_D_old.prg \
noise_writeback_check_9_to_D_new.prg \
noise_writeback_check_9_to_E_old.prg \
noise_writeback_check_9_to_F_old.prg \
noise_writeback_check_9_to_F_new.prg \
noise_writeback_check_A_to_8_old.prg \
noise_writeback_check_A_to_8_new.prg \
noise_writeback_check_A_to_9_old.prg \
noise_writeback_check_A_to_9_new.prg \
noise_writeback_check_A_to_A_old.prg \
noise_writeback_check_A_to_A_new.prg \
noise_writeback_check_A_to_B_old.prg \
noise_writeback_check_A_to_B_new.prg \
noise_writeback_check_A_to_C_old.prg \
noise_writeback_check_A_to_D_old.prg \
noise_writeback_check_A_to_D_new.prg \
noise_writeback_check_A_to_E_old.prg \
noise_writeback_check_A_to_E_new.prg \
noise_writeback_check_A_to_F_old.prg \
noise_writeback_check_A_to_F_new.prg \
noise_writeback_check_B_to_8_old.prg \
noise_writeback_check_B_to_9_old.prg \
noise_writeback_check_B_to_9_new.prg \
noise_writeback_check_B_to_A_old.prg \
noise_writeback_check_B_to_A_new.prg \
noise_writeback_check_B_to_B_old.prg \
noise_writeback_check_B_to_B_new.prg \
noise_writeback_check_B_to_D_old.prg \
noise_writeback_check_B_to_D_new.prg \
noise_writeback_check_B_to_E_old.prg \
noise_writeback_check_B_to_E_new.prg \
noise_writeback_check_B_to_F_old.prg \
noise_writeback_check_B_to_F_new.prg \
noise_writeback_check_C_to_8_old.prg \
noise_writeback_check_C_to_8_new.prg \
noise_writeback_check_C_to_9_old.prg \
noise_writeback_check_C_to_9_new.prg \
noise_writeback_check_C_to_A_old.prg \
noise_writeback_check_C_to_A_new.prg \
noise_writeback_check_C_to_B_old.prg \
noise_writeback_check_C_to_C_old.prg \
noise_writeback_check_C_to_D_old.prg \
noise_writeback_check_C_to_E_old.prg \
noise_writeback_check_C_to_E_new.prg \
noise_writeback_check_C_to_F_old.prg \
noise_writeback_check_C_to_F_new.prg \
noise_writeback_check_D_to_8_old.prg \
noise_writeback_check_D_to_8_new.prg \
noise_writeback_check_D_to_9_old.prg \
noise_writeback_check_D_to_9_new.prg \
noise_writeback_check_D_to_A_old.prg \
noise_writeback_check_D_to_B_old.prg \
noise_writeback_check_D_to_B_new.prg \
noise_writeback_check_D_to_C_old.prg \
noise_writeback_check_D_to_D_old.prg \
noise_writeback_check_D_to_D_new.prg \
noise_writeback_check_D_to_E_old.prg \
noise_writeback_check_D_to_F_old.prg \
noise_writeback_check_D_to_F_new.prg \
noise_writeback_check_E_to_8_old.prg \
noise_writeback_check_E_to_8_new.prg \
noise_writeback_check_E_to_9_old.prg \
noise_writeback_check_E_to_9_new.prg \
noise_writeback_check_E_to_A_old.prg \
noise_writeback_check_E_to_A_new.prg \
noise_writeback_check_E_to_B_old.prg \
noise_writeback_check_E_to_B_new.prg \
noise_writeback_check_E_to_C_old.prg \
noise_writeback_check_E_to_D_new.prg \
noise_writeback_check_E_to_E_old.prg \
noise_writeback_check_E_to_E_new.prg \
noise_writeback_check_E_to_F_old.prg \
noise_writeback_check_E_to_F_new.prg \
noise_writeback_check_F_to_8_old.prg \
noise_writeback_check_F_to_9_old.prg \
noise_writeback_check_F_to_9_new.prg \
noise_writeback_check_F_to_A_old.prg \
noise_writeback_check_F_to_A_new.prg \
noise_writeback_check_F_to_B_old.prg \
noise_writeback_check_F_to_B_new.prg \
noise_writeback_check_F_to_C_old.prg \
noise_writeback_check_F_to_D_old.prg \
noise_writeback_check_F_to_D_new.prg \
noise_writeback_check_F_to_E_old.prg \
noise_writeback_check_F_to_E_new.prg \
noise_writeback_check_F_to_F_old.prg \
noise_writeback_check_F_to_F_new.prg


all: $(TARGETS)

noise_writeback_check_8_to_8_old.prg: noise_writeback_check.asm
	acme -DWAVES=0 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_8_to_8_new.prg: noise_writeback_check.asm
	acme -DWAVES=0 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_8_to_9_old.prg: noise_writeback_check.asm
	acme -DWAVES=1 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_8_to_9_new.prg: noise_writeback_check.asm
	acme -DWAVES=1 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_8_to_A_old.prg: noise_writeback_check.asm
	acme -DWAVES=2 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_8_to_A_new.prg: noise_writeback_check.asm
	acme -DWAVES=2 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_8_to_B_old.prg: noise_writeback_check.asm
	acme -DWAVES=3 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_8_to_B_new.prg: noise_writeback_check.asm
	acme -DWAVES=3 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_8_to_C_old.prg: noise_writeback_check.asm
	acme -DWAVES=4 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_8_to_D_old.prg: noise_writeback_check.asm
	acme -DWAVES=5 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_8_to_D_new.prg: noise_writeback_check.asm
	acme -DWAVES=5 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_8_to_E_old.prg: noise_writeback_check.asm
	acme -DWAVES=6 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_8_to_E_new.prg: noise_writeback_check.asm
	acme -DWAVES=6 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_8_to_F_old.prg: noise_writeback_check.asm
	acme -DWAVES=7 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_8_to_F_new.prg: noise_writeback_check.asm
	acme -DWAVES=7 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_9_to_8_old.prg: noise_writeback_check.asm
	acme -DWAVES=8 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_9_to_8_new.prg: noise_writeback_check.asm
	acme -DWAVES=8 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_9_to_9_old.prg: noise_writeback_check.asm
	acme -DWAVES=9 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_9_to_9_new.prg: noise_writeback_check.asm
	acme -DWAVES=9 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_9_to_A_old.prg: noise_writeback_check.asm
	acme -DWAVES=10 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_9_to_B_old.prg: noise_writeback_check.asm
	acme -DWAVES=11 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_9_to_B_new.prg: noise_writeback_check.asm
	acme -DWAVES=11 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_9_to_C_old.prg: noise_writeback_check.asm
	acme -DWAVES=12 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_9_to_D_old.prg: noise_writeback_check.asm
	acme -DWAVES=13 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_9_to_D_new.prg: noise_writeback_check.asm
	acme -DWAVES=13 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_9_to_E_old.prg: noise_writeback_check.asm
	acme -DWAVES=14 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_9_to_F_old.prg: noise_writeback_check.asm
	acme -DWAVES=15 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_9_to_F_new.prg: noise_writeback_check.asm
	acme -DWAVES=15 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_A_to_8_old.prg: noise_writeback_check.asm
	acme -DWAVES=16 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_A_to_8_new.prg: noise_writeback_check.asm
	acme -DWAVES=16 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_A_to_9_old.prg: noise_writeback_check.asm
	acme -DWAVES=17 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_A_to_9_new.prg: noise_writeback_check.asm
	acme -DWAVES=17 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_A_to_A_old.prg: noise_writeback_check.asm
	acme -DWAVES=18 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_A_to_A_new.prg: noise_writeback_check.asm
	acme -DWAVES=18 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_A_to_B_old.prg: noise_writeback_check.asm
	acme -DWAVES=19 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_A_to_B_new.prg: noise_writeback_check.asm
	acme -DWAVES=19 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_A_to_C_old.prg: noise_writeback_check.asm
	acme -DWAVES=20 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_A_to_D_old.prg: noise_writeback_check.asm
	acme -DWAVES=21 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_A_to_D_new.prg: noise_writeback_check.asm
	acme -DWAVES=21 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_A_to_E_old.prg: noise_writeback_check.asm
	acme -DWAVES=22 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_A_to_E_new.prg: noise_writeback_check.asm
	acme -DWAVES=22 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_A_to_F_old.prg: noise_writeback_check.asm
	acme -DWAVES=23 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_A_to_F_new.prg: noise_writeback_check.asm
	acme -DWAVES=23 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_B_to_8_old.prg: noise_writeback_check.asm
	acme -DWAVES=24 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_B_to_9_old.prg: noise_writeback_check.asm
	acme -DWAVES=25 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_B_to_9_new.prg: noise_writeback_check.asm
	acme -DWAVES=25 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_B_to_A_old.prg: noise_writeback_check.asm
	acme -DWAVES=26 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_B_to_A_new.prg: noise_writeback_check.asm
	acme -DWAVES=26 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_B_to_B_old.prg: noise_writeback_check.asm
	acme -DWAVES=27 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_B_to_B_new.prg: noise_writeback_check.asm
	acme -DWAVES=27 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_B_to_C_old.prg: noise_writeback_check.asm
	acme -DWAVES=28 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_B_to_D_old.prg: noise_writeback_check.asm
	acme -DWAVES=29 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_B_to_D_new.prg: noise_writeback_check.asm
	acme -DWAVES=29 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_B_to_E_old.prg: noise_writeback_check.asm
	acme -DWAVES=30 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_B_to_E_new.prg: noise_writeback_check.asm
	acme -DWAVES=30 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_B_to_F_old.prg: noise_writeback_check.asm
	acme -DWAVES=31 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_B_to_F_new.prg: noise_writeback_check.asm
	acme -DWAVES=31 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_C_to_8_old.prg: noise_writeback_check.asm
	acme -DWAVES=32 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_C_to_8_new.prg: noise_writeback_check.asm
	acme -DWAVES=32 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_C_to_9_old.prg: noise_writeback_check.asm
	acme -DWAVES=33 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_C_to_9_new.prg: noise_writeback_check.asm
	acme -DWAVES=33 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_C_to_A_old.prg: noise_writeback_check.asm
	acme -DWAVES=34 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_C_to_A_new.prg: noise_writeback_check.asm
	acme -DWAVES=34 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_C_to_B_old.prg: noise_writeback_check.asm
	acme -DWAVES=35 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_C_to_C_old.prg: noise_writeback_check.asm
	acme -DWAVES=36 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_C_to_D_old.prg: noise_writeback_check.asm
	acme -DWAVES=37 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_C_to_E_old.prg: noise_writeback_check.asm
	acme -DWAVES=38 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_C_to_E_new.prg: noise_writeback_check.asm
	acme -DWAVES=38 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_C_to_F_old.prg: noise_writeback_check.asm
	acme -DWAVES=39 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_C_to_F_new.prg: noise_writeback_check.asm
	acme -DWAVES=39 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_D_to_8_old.prg: noise_writeback_check.asm
	acme -DWAVES=40 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_D_to_8_new.prg: noise_writeback_check.asm
	acme -DWAVES=40 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_D_to_9_old.prg: noise_writeback_check.asm
	acme -DWAVES=41 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_D_to_9_new.prg: noise_writeback_check.asm
	acme -DWAVES=41 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_D_to_A_old.prg: noise_writeback_check.asm
	acme -DWAVES=42 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_D_to_B_old.prg: noise_writeback_check.asm
	acme -DWAVES=43 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_D_to_B_new.prg: noise_writeback_check.asm
	acme -DWAVES=43 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_D_to_C_old.prg: noise_writeback_check.asm
	acme -DWAVES=44 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_D_to_D_old.prg: noise_writeback_check.asm
	acme -DWAVES=45 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_D_to_D_new.prg: noise_writeback_check.asm
	acme -DWAVES=45 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_D_to_E_old.prg: noise_writeback_check.asm
	acme -DWAVES=46 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_D_to_F_old.prg: noise_writeback_check.asm
	acme -DWAVES=47 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_D_to_F_new.prg: noise_writeback_check.asm
	acme -DWAVES=47 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_E_to_8_old.prg: noise_writeback_check.asm
	acme -DWAVES=48 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_E_to_8_new.prg: noise_writeback_check.asm
	acme -DWAVES=48 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_E_to_9_old.prg: noise_writeback_check.asm
	acme -DWAVES=49 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_E_to_9_new.prg: noise_writeback_check.asm
	acme -DWAVES=49 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_E_to_A_old.prg: noise_writeback_check.asm
	acme -DWAVES=50 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_E_to_A_new.prg: noise_writeback_check.asm
	acme -DWAVES=50 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_E_to_B_old.prg: noise_writeback_check.asm
	acme -DWAVES=51 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_E_to_B_new.prg: noise_writeback_check.asm
	acme -DWAVES=51 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_E_to_C_old.prg: noise_writeback_check.asm
	acme -DWAVES=52 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_E_to_D_new.prg: noise_writeback_check.asm
	acme -DWAVES=53 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_E_to_E_old.prg: noise_writeback_check.asm
	acme -DWAVES=54 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_E_to_E_new.prg: noise_writeback_check.asm
	acme -DWAVES=54 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_E_to_F_old.prg: noise_writeback_check.asm
	acme -DWAVES=55 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_E_to_F_new.prg: noise_writeback_check.asm
	acme -DWAVES=55 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_F_to_8_old.prg: noise_writeback_check.asm
	acme -DWAVES=56 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_F_to_9_old.prg: noise_writeback_check.asm
	acme -DWAVES=57 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_F_to_9_new.prg: noise_writeback_check.asm
	acme -DWAVES=57 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_F_to_A_old.prg: noise_writeback_check.asm
	acme -DWAVES=58 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_F_to_A_new.prg: noise_writeback_check.asm
	acme -DWAVES=58 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_F_to_B_old.prg: noise_writeback_check.asm
	acme -DWAVES=59 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_F_to_B_new.prg: noise_writeback_check.asm
	acme -DWAVES=59 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_F_to_C_old.prg: noise_writeback_check.asm
	acme -DWAVES=60 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_F_to_D_old.prg: noise_writeback_check.asm
	acme -DWAVES=61 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_F_to_D_new.prg: noise_writeback_check.asm
	acme -DWAVES=61 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_F_to_E_old.prg: noise_writeback_check.asm
	acme -DWAVES=62 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_F_to_E_new.prg: noise_writeback_check.asm
	acme -DWAVES=62 -DNEWSID=1 -f cbm -o $@ $<

noise_writeback_check_F_to_F_old.prg: noise_writeback_check.asm
	acme -DWAVES=63 -DNEWSID=0 -f cbm -o $@ $<

noise_writeback_check_F_to_F_new.prg: noise_writeback_check.asm
	acme -DWAVES=63 -DNEWSID=1 -f cbm -o $@ $<

clean:
	rm -f $(TARGETS)
