.PHONY: cbm2-burnin p500-burnin

all:

cbm2-burnin:
	../../trunk/vice/src/xcbm2 -model 610 -ntsc -drive8type 8050 -virtualdev +truedrive -8 cbm2-burnin.d80

p500-burnin:
	../../trunk/vice/src/xcbm5x0 -ntsc -drive8type 8050 -virtualdev +truedrive -8 p500-burnin.d80
