all: test01.prg \
	test02.prg \
	test03.prg \
	test04.prg \
	test05.prg \
	test06.prg \
	test07.prg \
	test08.prg \
	test09.prg \
	test10.prg \
	test11.prg \
	test12.prg

test01.prg: test01.asm
	64tass test01.asm -o test01.prg
test02.prg: test02.asm
	64tass test02.asm -o test02.prg
test03.prg: test03.asm
	64tass test03.asm -o test03.prg
test04.prg: test04.asm
	64tass test04.asm -o test04.prg
test05.prg: test05.asm
	64tass test05.asm -o test05.prg
test06.prg: test06.asm
	64tass test06.asm -o test06.prg
test07.prg: test07.asm
	64tass test07.asm -o test07.prg
test08.prg: test08.asm
	64tass test08.asm -o test08.prg
test09.prg: test09.asm
	64tass test09.asm -o test09.prg
test10.prg: test10.asm
	64tass test10.asm -o test10.prg
test11.prg: test11.asm
	64tass test11.asm -o test11.prg
test12.prg: test12.asm
	64tass test12.asm -o test12.prg

clean:
	$(RM) test01.prg
	$(RM) test02.prg
	$(RM) test03.prg
	$(RM) test04.prg
	$(RM) test05.prg
	$(RM) test06.prg
	$(RM) test07.prg
	$(RM) test08.prg
	$(RM) test09.prg
	$(RM) test10.prg
	$(RM) test11.prg
	$(RM) test12.prg
