
all: \
	mmuversion.prg \
	mmuswap-00.prg \
	mmuswap-01.prg \
	mmuswap-02.prg \
	mmuswap-03.prg \
	mmuswap-04.prg \
	mmuswap-05.prg \
	mmuswap-06.prg \
	mmuswap-07.prg \
	mmuswap-08.prg \
	mmuswap-09.prg \
	mmuswap-10.prg \
	mmuswap-11.prg \
	mmuswap-12.prg \
	mmuswap-13.prg \
	mmuswap-14.prg \
	mmuswap-15.prg \
	mmuswap-16.prg \
	mmuswap-17.prg \
	mmuswap-18.prg \
	mmuswap-19.prg \
	mmuswap-20.prg \
	mmuswap-21.prg \
	mmutest.prg \
	mmutest2.prg \
	mmuregister-should-not-mirror.prg \
	p0h-is-set-after-p0l.prg \
	p0h-rw-test.prg \
	p1h-is-set-after-p1l.prg \
	p1h-rw-test.prg

mmuversion.prg: mmuversion.asm
	acme -f cbm -o mmuversion.prg mmuversion.asm

mmuswap-00.prg: mmuswap-00.asm
	acme -f cbm -o mmuswap-00.prg mmuswap-00.asm

mmuswap-01.prg: mmuswap-01.asm
	acme -f cbm -o mmuswap-01.prg mmuswap-01.asm

mmuswap-02.prg: mmuswap-02.asm
	acme -f cbm -o mmuswap-02.prg mmuswap-02.asm

mmuswap-03.prg: mmuswap-03.asm
	acme -f cbm -o mmuswap-03.prg mmuswap-03.asm

mmuswap-04.prg: mmuswap-04.asm
	acme -f cbm -o mmuswap-04.prg mmuswap-04.asm

mmuswap-05.prg: mmuswap-05.asm
	acme -f cbm -o mmuswap-05.prg mmuswap-05.asm

mmuswap-06.prg: mmuswap-06.asm
	acme -f cbm -o mmuswap-06.prg mmuswap-06.asm

mmuswap-07.prg: mmuswap-07.asm
	acme -f cbm -o mmuswap-07.prg mmuswap-07.asm

mmuswap-08.prg: mmuswap-08.asm
	acme -f cbm -o mmuswap-08.prg mmuswap-08.asm

mmuswap-09.prg: mmuswap-09.asm
	acme -f cbm -o mmuswap-09.prg mmuswap-09.asm

mmuswap-10.prg: mmuswap-10.asm
	acme -f cbm -o mmuswap-10.prg mmuswap-10.asm

mmuswap-11.prg: mmuswap-11.asm
	acme -f cbm -o mmuswap-11.prg mmuswap-11.asm

mmuswap-12.prg: mmuswap-12.asm
	acme -f cbm -o mmuswap-12.prg mmuswap-12.asm

mmuswap-13.prg: mmuswap-13.asm
	acme -f cbm -o mmuswap-13.prg mmuswap-13.asm

mmuswap-14.prg: mmuswap-14.asm
	acme -f cbm -o mmuswap-14.prg mmuswap-14.asm

mmuswap-15.prg: mmuswap-15.asm
	acme -f cbm -o mmuswap-15.prg mmuswap-15.asm

mmuswap-16.prg: mmuswap-16.asm
	acme -f cbm -o mmuswap-16.prg mmuswap-16.asm

mmuswap-17.prg: mmuswap-17.asm
	acme -f cbm -o mmuswap-17.prg mmuswap-17.asm

mmuswap-18.prg: mmuswap-18.asm
	acme -f cbm -o mmuswap-18.prg mmuswap-18.asm

mmuswap-19.prg: mmuswap-19.asm
	acme -f cbm -o mmuswap-19.prg mmuswap-19.asm

mmuswap-20.prg: mmuswap-20.asm
	acme -f cbm -o mmuswap-20.prg mmuswap-20.asm

mmuswap-21.prg: mmuswap-21.asm
	acme -f cbm -o mmuswap-21.prg mmuswap-21.asm

mmutest.prg: mmutest.asm
	acme -f cbm -o mmutest.prg mmutest.asm

mmutest2.prg: mmutest2.asm
	acme -f cbm -o mmutest2.prg mmutest2.asm

mmuregister-should-not-mirror.prg: mmuregister-should-not-mirror.asm
	acme -f cbm -o mmuregister-should-not-mirror.prg mmuregister-should-not-mirror.asm

p0h-is-set-after-p0l.prg: p0h-is-set-after-p0l.asm
	acme -f cbm -o p0h-is-set-after-p0l.prg p0h-is-set-after-p0l.asm

p0h-rw-test.prg: p0h-rw-test.asm
	acme -f cbm -o p0h-rw-test.prg p0h-rw-test.asm
	
p1h-is-set-after-p1l.prg: p1h-is-set-after-p1l.asm
	acme -f cbm -o p1h-is-set-after-p1l.prg p1h-is-set-after-p1l.asm

p1h-rw-test.prg: p1h-rw-test.asm
	acme -f cbm -o p1h-rw-test.prg p1h-rw-test.asm
	
clean:
	rm -f mmuversion.prg mmutest2.prg mmutest.prg mmuregister-should-not-mirror.prg
	rm -f p0h-is-set-after-p0l.prg p0h-rw-test.prg
	rm -f p1h-is-set-after-p1l.prg p1h-rw-test.prg
