
TARGETS=\
	autostart-c64-none.prg \
	autostart-c64-tde.prg \
	autostart-c64-vdrive.prg \
	autostart-c64-vfs.prg \
	autostart-c64-tde-disk.prg \
	autostart-c64-vdrive-disk.prg \
	autostart-c64-none-image.prg \
	autostart-c64-tde-image.prg \
	autostart-c64-vdrive-image.prg \
	\
	autostart-c64-none.d64 \
	autostart-c64-tde.d64 \
	autostart-c64-vdrive.d64 \
	autostart-c64-vfs.d64 \
	autostart-c64-tde-disk.d64 \
	autostart-c64-vdrive-disk.d64 \
	autostart-c64-none-image.d64 \
	autostart-c64-tde-image.d64 \
	autostart-c64-vdrive-image.d64 \
	\
	autostart-c64-none.t64 \
	autostart-c64-tde.t64 \
	autostart-c64-vfs.t64 \
	\
	autostart-c64-567-vfs.prg \
	autostart-c64-5678-vfs.prg \
	autostart-c64-5678901-vfs.prg \
	autostart-c64-56789012-vfs.prg \
	autostart-c64-56789012345678901234567890123456789012345678901-vfs.prg \
	\
	autostart-c128-none.prg \
	autostart-c128-tde.prg \
	autostart-c128-vdrive.prg \
	autostart-c128-vfs.prg \
	autostart-c128-tde-disk.prg \
	autostart-c128-vdrive-disk.prg \
	autostart-c128-none-image.prg \
	autostart-c128-tde-image.prg \
	autostart-c128-vdrive-image.prg \
	\
	autostart-c128-none.d64 \
	autostart-c128-tde.d64 \
	autostart-c128-vdrive.d64 \
	autostart-c128-vfs.d64 \
	autostart-c128-tde-disk.d64 \
	autostart-c128-vdrive-disk.d64 \
	autostart-c128-none-image.d64 \
	autostart-c128-tde-image.d64 \
	autostart-c128-vdrive-image.d64 \
	\
	autostart-c128-none.t64 \
	autostart-c128-tde.t64 \
	autostart-c128-vfs.t64 \
	\
	autostart-vic20-none.prg \
	autostart-vic20-tde.prg \
	autostart-vic20-vdrive.prg \
	autostart-vic20-vfs.prg \
	autostart-vic20-tde-disk.prg \
	autostart-vic20-vdrive-disk.prg \
	autostart-vic20-none-image.prg \
	autostart-vic20-tde-image.prg \
	autostart-vic20-vdrive-image.prg \
	\
	autostart-vic20-none.d64 \
	autostart-vic20-tde.d64 \
	autostart-vic20-vdrive.d64 \
	autostart-vic20-vfs.d64 \
	autostart-vic20-tde-disk.d64 \
	autostart-vic20-vdrive-disk.d64 \
	autostart-vic20-none-image.d64 \
	autostart-vic20-tde-image.d64 \
	autostart-vic20-vdrive-image.d64 \
	\
	autostart-vic20-none.t64 \
	autostart-vic20-tde.t64 \
	autostart-vic20-vfs.t64 \
	\
	autostart-plus4-none.prg \
	autostart-plus4-tde.prg \
	autostart-plus4-vdrive.prg \
	autostart-plus4-vfs.prg \
	autostart-plus4-tde-disk.prg \
	autostart-plus4-vdrive-disk.prg \
	autostart-plus4-none-image.prg \
	autostart-plus4-tde-image.prg \
	autostart-plus4-vdrive-image.prg \
	\
	autostart-plus4-none.d64 \
	autostart-plus4-tde.d64 \
	autostart-plus4-vdrive.d64 \
	autostart-plus4-vfs.d64 \
	autostart-plus4-tde-disk.d64 \
	autostart-plus4-vdrive-disk.d64 \
	autostart-plus4-none-image.d64 \
	autostart-plus4-tde-image.d64 \
	autostart-plus4-vdrive-image.d64 \
	\
	autostart-plus4-none.t64 \
	autostart-plus4-tde.t64 \
	autostart-plus4-vfs.t64 \
	\
	autostart-pet-none.prg \
	autostart-pet-tde.prg \
	autostart-pet-vdrive.prg \
	autostart-pet-vfs.prg \
	autostart-pet-tde-disk.prg \
	autostart-pet-vdrive-disk.prg \
	autostart-pet-none-image.prg \
	autostart-pet-tde-image.prg \
	autostart-pet-vdrive-image.prg \
	\
	autostart-pet-none.d82 \
	autostart-pet-tde.d82 \
	autostart-pet-vdrive.d82 \
	autostart-pet-vfs.d82 \
	autostart-pet-tde-disk.d82 \
	autostart-pet-vdrive-disk.d82 \
	autostart-pet-none-image.d82 \
	autostart-pet-tde-image.d82 \
	autostart-pet-vdrive-image.d82 \
	\
	autostart-pet-none.t64 \
	autostart-pet-tde.t64 \
	autostart-pet-vfs.t64 \
	\
	autostart-cbm510-none.prg \
	autostart-cbm510-tde.prg \
	autostart-cbm510-vdrive.prg \
	autostart-cbm510-vfs.prg \
	autostart-cbm510-tde-disk.prg \
	autostart-cbm510-vdrive-disk.prg \
	autostart-cbm510-none-image.prg \
	autostart-cbm510-tde-image.prg \
	autostart-cbm510-vdrive-image.prg \
	\
	autostart-cbm510-none.d82 \
	autostart-cbm510-tde.d82 \
	autostart-cbm510-vdrive.d82 \
	autostart-cbm510-vfs.d82 \
	autostart-cbm510-tde-disk.d82 \
	autostart-cbm510-vdrive-disk.d82 \
	autostart-cbm510-none-image.d82 \
	autostart-cbm510-tde-image.d82 \
	autostart-cbm510-vdrive-image.d82 \
	\
	autostart-cbm610-none.prg \
	autostart-cbm610-tde.prg \
	autostart-cbm610-vdrive.prg \
	autostart-cbm610-vfs.prg \
	autostart-cbm610-tde-disk.prg \
	autostart-cbm610-vdrive-disk.prg \
	autostart-cbm610-none-image.prg \
	autostart-cbm610-tde-image.prg \
	autostart-cbm610-vdrive-image.prg \
	\
	autostart-cbm610-none.d82 \
	autostart-cbm610-tde.d82 \
	autostart-cbm610-vdrive.d82 \
	autostart-cbm610-vfs.d82 \
	autostart-cbm610-tde-disk.d82 \
	autostart-cbm610-vdrive-disk.d82 \
	autostart-cbm610-none-image.d82 \
	autostart-cbm610-tde-image.d82 \
	autostart-cbm610-vdrive-image.d82

all: $(TARGETS)

autostart-c64-none.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@
autostart-c64-tde.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@
autostart-c64-vdrive.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@
autostart-c64-vfs.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=1 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@
autostart-c64-tde-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@
autostart-c64-vdrive-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@

autostart-c64-none-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@
autostart-c64-tde-image.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@
autostart-c64-vdrive-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -o $@
	
autostart-c64-567-vfs.prg: autostart-c64-vfs.prg
	cp autostart-c64-vfs.prg autostart-c64-567-vfs.prg
autostart-c64-5678-vfs.prg: autostart-c64-vfs.prg
	cp autostart-c64-vfs.prg autostart-c64-5678-vfs.prg
autostart-c64-5678901-vfs.prg: autostart-c64-vfs.prg
	cp autostart-c64-vfs.prg autostart-c64-5678901-vfs.prg
autostart-c64-56789012-vfs.prg: autostart-c64-vfs.prg
	cp autostart-c64-vfs.prg autostart-c64-56789012-vfs.prg
autostart-c64-56789012345678901234567890123456789012345678901-vfs.prg: autostart-c64-vfs.prg
	cp autostart-c64-vfs.prg autostart-c64-56789012345678901234567890123456789012345678901-vfs.prg
	
autostart-c64-none.d64: autostart-c64-none.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c64-tde.d64: autostart-c64-tde.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c64-vdrive.d64: autostart-c64-vdrive.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c64-vfs.d64: autostart-c64-vfs.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c64-tde-disk.d64: autostart-c64-tde-disk.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c64-vdrive-disk.d64: autostart-c64-vdrive-disk.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c64-none-image.d64: autostart-c64-none-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c64-tde-image.d64: autostart-c64-tde-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c64-vdrive-image.d64: autostart-c64-vdrive-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"

autostart-c64-none.t64: autostart-c64-none.prg
	t64fix -c autostart-c64-none.t64 autostart-c64-none.prg
autostart-c64-tde.t64: autostart-c64-tde.prg
	t64fix -c autostart-c64-tde.t64 autostart-c64-tde.prg
autostart-c64-vfs.t64: autostart-c64-vfs.prg
	t64fix -c autostart-c64-vfs.t64 autostart-c64-vfs.prg

autostart-c128-none.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@
autostart-c128-tde.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@
autostart-c128-vdrive.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@
autostart-c128-vfs.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=1 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@
autostart-c128-tde-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@
autostart-c128-vdrive-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@

autostart-c128-none-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@
autostart-c128-tde-image.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@
autostart-c128-vdrive-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=55295 -DBORDERCOLOR=53280 -DBGCOLOR=53281 -E $< | grep -v "^#" | petcat -w2 -l 1c01 -o $@
	
autostart-c128-none.d64: autostart-c128-none.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c128-tde.d64: autostart-c128-tde.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c128-vdrive.d64: autostart-c128-vdrive.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c128-vfs.d64: autostart-c128-vfs.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c128-tde-disk.d64: autostart-c128-tde-disk.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c128-vdrive-disk.d64: autostart-c128-vdrive-disk.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c128-none-image.d64: autostart-c128-none-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c128-tde-image.d64: autostart-c128-tde-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-c128-vdrive-image.d64: autostart-c128-vdrive-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"

autostart-c128-none.t64: autostart-c128-none.prg
	t64fix -c autostart-c128-none.t64 autostart-c128-none.prg
autostart-c128-tde.t64: autostart-c128-tde.prg
	t64fix -c autostart-c128-tde.t64 autostart-c128-tde.prg
autostart-c128-vfs.t64: autostart-c128-vfs.prg
	t64fix -c autostart-c128-vfs.t64 autostart-c128-vfs.prg

autostart-vic20-none.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@
autostart-vic20-tde.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@
autostart-vic20-vdrive.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@
autostart-vic20-vfs.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=1 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@
autostart-vic20-tde-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@
autostart-vic20-vdrive-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@

autostart-vic20-none-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@
autostart-vic20-tde-image.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@
autostart-vic20-vdrive-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=37135 -DBORDERCOLOR=36879 -DBGCOLOR=36879 -E $< | grep -v "^#" | petcat -l 1201 -w2 -o $@

autostart-vic20-none.d64: autostart-vic20-none.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-vic20-tde.d64: autostart-vic20-tde.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-vic20-vdrive.d64: autostart-vic20-vdrive.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-vic20-vfs.d64: autostart-vic20-vfs.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-vic20-tde-disk.d64: autostart-vic20-tde-disk.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-vic20-vdrive-disk.d64: autostart-vic20-vdrive-disk.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-vic20-none-image.d64: autostart-vic20-none-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-vic20-tde-image.d64: autostart-vic20-tde-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-vic20-vdrive-image.d64: autostart-vic20-vdrive-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"

autostart-vic20-none.t64: autostart-vic20-none.prg
	t64fix -c autostart-vic20-none.t64 autostart-vic20-none.prg
autostart-vic20-tde.t64: autostart-vic20-tde.prg
	t64fix -c autostart-vic20-tde.t64 autostart-vic20-tde.prg
autostart-vic20-vfs.t64: autostart-vic20-vfs.prg
	t64fix -c autostart-vic20-vfs.t64 autostart-vic20-vfs.prg

autostart-plus4-none.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@
autostart-plus4-tde.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@
autostart-plus4-vdrive.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@
autostart-plus4-vfs.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=1 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@
autostart-plus4-tde-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@
autostart-plus4-vdrive-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@

autostart-plus4-none-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@
autostart-plus4-tde-image.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@
autostart-plus4-vdrive-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=64975 -DBORDERCOLOR=65305 -DBGCOLOR=65301 -E $< | grep -v "^#" | petcat -l 1001 -w2 -o $@

autostart-plus4-none.d64: autostart-plus4-none.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-plus4-tde.d64: autostart-plus4-tde.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-plus4-vdrive.d64: autostart-plus4-vdrive.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-plus4-vfs.d64: autostart-plus4-vfs.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-plus4-tde-disk.d64: autostart-plus4-tde-disk.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-plus4-vdrive-disk.d64: autostart-plus4-vdrive-disk.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-plus4-none-image.d64: autostart-plus4-none-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-plus4-tde-image.d64: autostart-plus4-tde-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"
autostart-plus4-vdrive-image.d64: autostart-plus4-vdrive-image.prg
	c1541 -format "testdisk,00" d64 $@ -write $< "test"

autostart-plus4-none.t64: autostart-plus4-none.prg
	t64fix -c autostart-plus4-none.t64 autostart-plus4-none.prg
autostart-plus4-tde.t64: autostart-plus4-tde.prg
	t64fix -c autostart-plus4-tde.t64 autostart-plus4-tde.prg
autostart-plus4-vfs.t64: autostart-plus4-vfs.prg
	t64fix -c autostart-plus4-vfs.t64 autostart-plus4-vfs.prg

autostart-pet-none.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@
autostart-pet-tde.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@
autostart-pet-vdrive.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@
autostart-pet-vfs.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=1 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@
autostart-pet-tde-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@
autostart-pet-vdrive-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@

autostart-pet-none-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@
autostart-pet-tde-image.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@
autostart-pet-vdrive-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=35839 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0401 -w2 -o $@

autostart-pet-none.d82: autostart-pet-none.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-pet-tde.d82: autostart-pet-tde.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-pet-vdrive.d82: autostart-pet-vdrive.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-pet-vfs.d82: autostart-pet-vfs.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-pet-tde-disk.d82: autostart-pet-tde-disk.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-pet-vdrive-disk.d82: autostart-pet-vdrive-disk.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-pet-none-image.d82: autostart-pet-none-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-pet-tde-image.d82: autostart-pet-tde-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-pet-vdrive-image.d82: autostart-pet-vdrive-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"

autostart-pet-none.t64: autostart-pet-none.prg
	t64fix -c autostart-pet-none.t64 autostart-pet-none.prg
autostart-pet-tde.t64: autostart-pet-tde.prg
	t64fix -c autostart-pet-tde.t64 autostart-pet-tde.prg
autostart-pet-vfs.t64: autostart-pet-vfs.prg
	t64fix -c autostart-pet-vfs.t64 autostart-pet-vfs.prg

autostart-cbm510-none.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm510-tde.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm510-vdrive.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm510-vfs.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=1 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm510-tde-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm510-vdrive-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@

autostart-cbm510-none-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm510-tde-image.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm510-vdrive-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@

autostart-cbm510-none.d82: autostart-cbm510-none.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm510-tde.d82: autostart-cbm510-tde.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm510-vdrive.d82: autostart-cbm510-vdrive.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm510-vfs.d82: autostart-cbm510-vfs.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm510-tde-disk.d82: autostart-cbm510-tde-disk.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm510-vdrive-disk.d82: autostart-cbm510-vdrive-disk.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm510-none-image.d82: autostart-cbm510-none-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm510-tde-image.d82: autostart-cbm510-tde-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm510-vdrive-image.d82: autostart-cbm510-vdrive-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"

# kernal traps are not implemented, and tape generally only works in the first
# kernal version
#autostart-cbm510-none.t64: autostart-cbm510-none.prg
#	t64fix -c autostart-cbm510-none.t64 autostart-cbm510-none.prg
#autostart-cbm510-tde.t64: autostart-cbm510-tde.prg
#	t64fix -c autostart-cbm510-tde.t64 autostart-cbm510-tde.prg
#autostart-cbm510-vfs.t64: autostart-cbm510-vfs.prg
#	t64fix -c autostart-cbm510-vfs.t64 autostart-cbm510-vfs.prg

autostart-cbm610-none.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm610-tde.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm610-vdrive.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm610-vfs.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=1 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm610-tde-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm610-vdrive-disk.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=1 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@

autostart-cbm610-none-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=0 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm610-tde-image.prg: autostart.bas
	cpp -DEXPECT_TDE=1 -DEXPECT_VDRIVE=0 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@
autostart-cbm610-vdrive-image.prg: autostart.bas
	cpp -DEXPECT_TDE=0 -DEXPECT_VDRIVE=1 -DEXPECT_VFS=0 -DEXPECT_AUTOSTART_DISK=0 -DEXPECT_DISKIMAGE=1 -DDEBUGREG=56063 -DBORDERCOLOR=255 -DBGCOLOR=255 -E $< | grep -v "^#" | petcat -l 0003 -w2 -o $@

autostart-cbm610-none.d82: autostart-cbm610-none.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm610-tde.d82: autostart-cbm610-tde.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm610-vdrive.d82: autostart-cbm610-vdrive.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm610-vfs.d82: autostart-cbm610-vfs.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm610-tde-disk.d82: autostart-cbm610-tde-disk.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm610-vdrive-disk.d82: autostart-cbm610-vdrive-disk.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm610-none-image.d82: autostart-cbm610-none-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm610-tde-image.d82: autostart-cbm610-tde-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"
autostart-cbm610-vdrive-image.d82: autostart-cbm610-vdrive-image.prg
	c1541 -format "testdisk,00" d82 $@ -write $< "test"

# kernal traps are not implemented, and tape generally only works in the first
# kernal version
#autostart-cbm610-none.t64: autostart-cbm610-none.prg
#	t64fix -c autostart-cbm610-none.t64 autostart-cbm610-none.prg
#autostart-cbm610-tde.t64: autostart-cbm610-tde.prg
#	t64fix -c autostart-cbm610-tde.t64 autostart-cbm610-tde.prg
#autostart-cbm610-vfs.t64: autostart-cbm610-vfs.prg
#	t64fix -c autostart-cbm610-vfs.t64 autostart-cbm610-vfs.prg

.PHONY: test clean
	
test: $(TARGETS)
	./autostart.sh all
testverbose: $(TARGETS)
	./autostart.sh --verbose all

clean:
	$(RM) *.prg
	$(RM) *.t64
