all: snestest-c64.prg snestest-c128.prg snestest-vic20.prg snestest-pet40.prg snestest-pet80.prg

snestest-c64.prg: snestest-c64.asm
	acme snestest-c64.asm

snestest-c128.prg: snestest-c128.asm
	acme snestest-c128.asm

snestest-vic20.prg: snestest-vic20.asm
	acme snestest-vic20.asm

snestest-pet40.prg: snestest-pet40.asm
	acme snestest-pet40.asm

snestest-pet80.prg: snestest-pet80.asm
	acme snestest-pet80.asm
