
.PHONY: zerox-8565r2 zerox-8565r2 zerox-6569r1 zerox-6569r5_1886_s

all: zerox-8565r2 zerox-6569r1 zerox-6569r5_1886_s

zerox-8565r2:
	./anim4zerox.sh ../../../../crtemulation/grid/grid.png  ./zerox-8565r2/8565r2_grid.png                    ./zerox-8565r2/8565r2_grid
	./anim4zerox.sh ../references/modesplit.prg-8565.png    ./zerox-8565r2/8565r2_modesplit.png               ./zerox-8565r2/8565r2_modesplit

zerox-6569r1:
	./anim4zerox.sh ../../../../crtemulation/grid/grid.png  ./zerox-6569r1/6569r1_grid.png                    ./zerox-6569r1/6569r1_grid
	./anim4zerox.sh ../references/modesplit.prg.png         ./zerox-6569r1/6569r1_modesplit.png               ./zerox-6569r1/6569r1_modesplit

zerox-6569r5_1886_s:
	./anim4zerox.sh ../../../../crtemulation/grid/grid.png  ./zerox-6569r5_1886_s/6569R5_1886_S_grid.png      ./zerox-6569r5_1886_s/6569R5_1886_S_grid
	./anim4zerox.sh ../references/modesplit.prg.png         ./zerox-6569r5_1886_s/6569R5_1886_S_modesplit.png ./zerox-6569r5_1886_s/6569R5_1886_S_modesplit
	
