
all: crtc0.prg \
	crtc1.prg \
	crtc2.prg \
	crtc3.prg \
	crtc4.prg \
	crtc5.prg \
	crtc6.prg \
	crtc7.prg \
	crtc8.prg \
	crtc9.prg \
	crtc10.prg \
	crtc11.prg \
	crtc12.prg \
	crtc13.prg

crtc0.prg: crtc0.a65
	xa -o crtc0.prg crtc0.a65
crtc1.prg: crtc1.a65
	xa -o crtc1.prg crtc1.a65
crtc2.prg: crtc2.a65
	xa -o crtc2.prg crtc2.a65
crtc3.prg: crtc3.a65
	xa -o crtc3.prg crtc3.a65
crtc4.prg: crtc4.a65
	xa -o crtc4.prg crtc4.a65
crtc5.prg: crtc5.a65
	xa -o crtc5.prg crtc5.a65
crtc6.prg: crtc6.a65
	xa -o crtc6.prg crtc6.a65
crtc7.prg: crtc7.a65
	xa -o crtc7.prg crtc7.a65
crtc8.prg: crtc8.a65
	xa -o crtc8.prg crtc8.a65
crtc9.prg: crtc9.a65
	xa -o crtc9.prg crtc9.a65
crtc10.prg: crtc10.a65
	xa -o crtc10.prg crtc10.a65
crtc11.prg: crtc11.a65
	xa -o crtc11.prg crtc11.a65
crtc12.prg: crtc12.a65
	xa -o crtc12.prg crtc12.a65
crtc13.prg: crtc13.a65
	xa -o crtc13.prg crtc13.a65

clean:
	$(RM) crtc0.prg \ 
		crtc1.prg \
		crtc2.prg \
		crtc3.prg \
		crtc4.prg \
		crtc5.prg \
		crtc6.prg \
		crtc7.prg \
		crtc8.prg \
		crtc9.prg \
		crtc10.prg \
		crtc11.prg \
		crtc12.prg \
		crtc13.prg
